### ISSUE TITLE
What am i doing?

### ISSUE THREAD

**Issue by Crisp-Casper** [synacktraa/ani-skip#1]
im not sure what im supposed to be expected to do after running the script
`./ani-skip "Ansatsu Kyoushitsu (TV) (22 episodes)" 1
--script-opts=skip-start_time=211.499,skip-end_time=301.499`
i receive this then i am left unclear am i supposed to download the video and pipe it as shown in the second example?

**Comment by Crisp-Casper** [comment]
to be clear i ran ./ani-skip "Ansatsu Kyoushitsu (TV) (22 episodes)" 1 and got the rest as a result

**Comment by synacktraa** [comment]
Hey, this script for generateing `--script-opts` flag for mpv player. It is not for playing anime but for generating script opts flag with start and end time of opening sequence. It can be used like an API with Anime player which uses mpv. You can refer mpv's manpage for `--script-opts` flag.

`ani-skip` takes anime title and episode number as first and second argument respectively. It generates start and end time of the opening sequence. It's still not implemented in any CLI anime player so for now if you want play any anime episode you'll first have to download it and then use this script like this to play it: `./ani-skip "Ansatsu Kyoushitsu (TV) (22 episodes)" 1 | xargs -I {} mpv --script=~/.config/mpv/scripts/skip.lua {} "downloaded_ansatsu_kyoushitsu_1st_ep_file.mp4"`

`downloaded_ansatsu_kyoushitsu_1st_ep_file.mp4` is the file you'll have to download from any anime downloader for now.

I'll soon implement it in `ani-cli` or will extend this script to play anime

**Comment by Crisp-Casper** [comment]
alright awesome! i was just unsure of what i was doing I'm really looking forward to this being a full fledged feature!

**Comment by synacktraa** [comment]
Sure! I'll implement it soon.
