### ISSUE TITLE
Windows version

### ISSUE THREAD

**Issue by Rickyrvxlovet** [synacktraa/ani-skip#10]
Please make it available for windows without scoop and other things

**Comment by synacktraa** [comment]
Scoop is used for installing mpv, fzf and git. You can use other tools like chocolatey to install them but I personally like scoop. You can also install the standalone binaries from their GitHub repositories but you will have to add path environment variables.

**Comment by Rickyrvxlovet** [comment]
> Scoop is used for installing mpv, fzf and git. You can use other tools like chocolatey to install them but I personally like scoop. You can also install the standalone binaries from their GitHub repositories but you will have to add path environment variables.


Okay. But how can I change the directory from temp to other locations? 

Is there a way to change the temp file name to the anime episode?

**Comment by synacktraa** [comment]
Do you mean episode chapters temp file?

**Comment by Rickyrvxlovet** [comment]
> Do you mean episode chapters temp file?

Yeah

**Comment by synacktraa** [comment]
I think I'll just make an update where the user can decide with a flag if the chapter files should be persisted.

**Comment by Rickyrvxlovet** [comment]
> I think I'll just make an update where the user can decide with a flag if the chapter files should be persisted.

Than you. But can you guide me how can I change it rn?

**Comment by synacktraa** [comment]
Go to /tmp directory, you'll find all the files. You will need to check the content because the filenames are gibberish. Also they are temporary so if you restart your pc they will get deleted
