### ISSUE TITLE
ani-cli integration

### ISSUE THREAD

**Issue by AzureOrange404** [synacktraa/ani-skip#3]
Hi,

I tried to implement use of ani-skip into ani-cli and it works.

But I realised, ani-skip is not working for all animes and I don't have time to look into it right now.
e. g. try: ani-skip "Fairy Tail (176 episodes)" 90

I'll still create a [pull request](https://github.com/pystardust/ani-cli/pull/1231) to ani-cli and let the decision making to the ani-cli devs.

**Comment by synacktraa** [comment]
Hey,

This script uses [aniskip](https://github.com/lexesjan/typescript-aniskip-extension/tree/main/src/api/aniskip-http-client) API, If there's any anime missing, you can contribute or ask for help in their [discord](https://discord.com/invite/UqT55CbrbE) server.

Kind regards.
