### ISSUE TITLE
Unable to install on android without su

### ISSUE THREAD

**Issue by EbanNox** [synacktraa/ani-skip#5]
As mentioned... the method declare on the githup page is invalid for android unless u r rooted witch is unessesery. It this packade declare it self to run on android the pls include proper install instructions on the github page

**Comment by EbanNox** [comment]
Wow, super active git, ik amazed on how much has been implemented, and how well maintained everything is, not abandoned at all

**Comment by synacktraa** [comment]
> Wow, super active git, ik amazed on how much has been implemented, and how well maintained everything is, not abandoned at all

Thanks for your comment! I’ve actually decided to pass the maintenance of the repository to others due to other commitments. I’m glad you found it useful, and I’m sure the new maintainers will keep it in good shape.
