### ISSUE TITLE
How to install ani-skip on windows?

### ISSUE THREAD

**Issue by M0rkulv** [synacktraa/ani-skip#6]
how can install ani-skip on windows i have ani-cli and mpv install with scoop 
but i cant findt a way to use ani-skip on windows

**Comment by ivdccxi** [comment]
I would appreciate intructions on this. I installed mpv using winget and dont know what path i should use for copying the script

**Comment by synacktraa** [comment]
> I would appreciate intructions on this. I installed mpv using winget and dont know what path i should use for copying the script

you can find the installed packages using `winget --info`, but ani-skip is a bash script so it can only run on WSL if you're on windows.

**Comment by synacktraa** [comment]
I have resolved bugs related to windows support.
Here's the release: https://github.com/synacktraa/ani-skip/releases/tag/1.0.0

Make sure you're using git bash. Thankyou.
